kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm

steps:
- name: python
  image: python:3.9
  commands:
    - pip3 install bcrypt==3.1.7
    - pip3 install -r requirements.test.txt --extra-index-url https://www.piwheels.org/simple
    - pytest
    - flake8 custom_components tests

- name: hassfest
  image: homeassistant/home-assistant:beta
  commands:
    - pip3 install pipdeptree==1.0.0 stdlib-list==0.7.0 tqdm==4.48.2
    - bashio ./drone/hassfest.sh